Algoritmo "question1"

Var
   num_1, num_2: inteiro;


Inicio

      Escreval("Informe o primeiro numero: ")
      leia(num_1)
      
      Escreval("Informe o segundo numero: ")
      leia(num_2)
      
      se (num_1 > num_2) entao
         Escreval("O numero um e maior que o numero dois")
      senao
         Escreval("O numero dois e maior que o numero um")
      fimse
      

Fimalgoritmo