Algoritmo "question3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/11/2023
Var
// Seção de Declarações das variáveis
   idade: inteiro;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Informe a idade")
   leia(idade)
   
   se (idade >= 18) entao
      escreval("Maior de idade!")
   senao
        escreval("Menor de idade!")
   fimse


Fimalgoritmo